<?php

define('APP_ID', '183864661712986');
define('APP_SECRET', '453c0ad8f9f39561a9021457610ad0ad');
define('REDIRECT_URI', 'http://localhost:5000?q=friendfinder/');

function get_app_token_url($scope = '') {
	//if a scope is provided, generate a url with a scope
	if ($scope) {
		$params = array(
			'client_id' => APP_ID,
			'redirect_uri' => REDIRECT_URI,
			'scope' => $scope,
		);
		return 'https://facebook.com/dialog/oauth?' . http_build_query($params, '', '&');
	}
	//if no scope is provided, return a url with no scope param
	else {
		$params = array(
			'client_id' => APP_ID,
			'redirect_uri' => REDIRECT_URI,
		);
		return 'https://facebook.com/dialog/oauth?' . http_build_query($params, '', '&');
	}
}

function get_app_token() {
	//get facebook app token by grabbing it from the url once redirected from facebook
	$url = $_SERVER['REQUEST_URI'];
	$urlExploded = explode("&", $url);
	$code = (split("=", $urlExploded[1]));
	$appToken = $code[1];
	
	return $appToken;
}

function get_client_token($token) {
	//get the facebook client token by scraping the contents of the returned JSON
	$params = array(
		'client_id' => APP_ID,
		'redirect_uri' => REDIRECT_URI,
		'client_secret' => APP_SECRET,
		'type' => 'client_cred',
		'code' => $token,
	);
	
	$tokenJSON = fb_call('oauth/access_token?' . http_build_query($params, '', '&'));
	$tokenArray = split('=', $tokenJSON);
	$clientToken = $tokenArray[1];
	
	return $clientToken;
}

function fb_url($call, $token) {
	//generate a url to access facebook data
	return "https://graph.facebook.com/". $call ."&access_token=". $token;
}

function fb_call($call, $token=0) {
	/*if a call includes a token, run the query with the token, 
	grabbing and decoding the returned JSON*/
	if ($token) { 
		$init = curl_init("https://graph.facebook.com/". $call. "&access_token=". $token);
		curl_setopt($init, CURLOPT_RETURNTRANSFER, true);
		$encodedJSON = curl_exec($init);
		curl_close($init);
		$decodedJSON = json_decode($encodedJSON, true);
	}
	//if no token is provided, run the query without a token
	else {
		$init = curl_init("https://graph.facebook.com/". $call);
		curl_setopt($init, CURLOPT_RETURNTRANSFER, true);
		$decodedJSON = curl_exec($init);
		curl_close($init);
	}
	
	return $decodedJSON;
}

function friendfinder_help($path, $arg) {
	$output = '';
	switch ($path) {
		case "admin/help#friend":
			$output = '<p>'. t("Displays Facebook friends and allows interaction within Drupal") .'</p>';
			break;
	}
	return $output;
}

function friendfinder_perm() {
	return array('access friendfinder content');
}

function friendfinder_all() {
	
	$output = '';
	$username = variable_get("friendfinder_username", '');
	$appToken = get_app_token();
	
	//if the client configured their username, check for a valid app token
	if ($username){
		//if an app token exists, get a client token
		if ($appToken) {
			$clientToken = get_client_token($appToken);
			//get a list of 4 of the user's Facebook friends 
			$friends = fb_call($username . "/friends&limit=4", $clientToken); 
			//add the photo and name of the friends to the output
			$output .= "<p>Here are some of your Facebook friends: </p>";
			foreach ($friends['data'] as $friend) {
					$metadata = fb_call($friend['id'], $clientToken);
					$profile = "http://www.facebook.com/". $friend['id'];
					$output .= "<div id='fbfriends'>";
					$output .=  l("<img src='". fb_url($friend['id'] ."/picture", $clientToken) ."' />", $profile, array('html' => true));
					$output .= "<p>". l($metadata['name'], $profile) ."</p>";
					$output .= "</div>";
				}
		
		}
		//if no app token exists, send the client through the facebook auth process
		else {
			$output .= l('Login to Facebook', get_app_token_url());
		}
		$output .= '<br /><br />Not ' . $username . '? Enter a different Facebook username ' . l('here', 'admin/settings/friendfinder') . '.';
	}
	//if no username has been configured, send client to friendfinder settings page
	else {
		$output .= "Before using FriendFinder you must ". l('enter your Facebook username', 'admin/settings/friendfinder') .".";
	}

	return $output;
}

function friendfinder_config() {
	$form = array();
	
	$form['friendfinder_username'] = array(
		'#type' => 'textfield',
		'#title' => t('Facebook username'),
		'#default_value' => variable_get('friendfinder_username', ''),
		'#size' => 20,
		'#description' => t('Found at the end of your Facebook profile URL (http://www.facebook.com/xxxxxxxx)'),
	);
	
	return system_settings_form($form);
}

function friendfinder_menu() {
	$items = array();
	
	$items['friendfinder'] = array(
		'title' => 'FriendFinder',
		'page callback' => 'friendfinder_all',
		'access arguments' => array('access friendfinder content'),
		'weight' => 9,
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['admin/settings/friendfinder'] = array(
		'title' => t('FriendFinder module settings'),
		'description' => t('FriendFinder configuration page'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('friendfinder_config'),
		'access arguments' => array('access friendfinder content'),
		'type' => MENU_CALLBACK,
	);
	
	return $items;
}